Repository Monadical-SAS/reflector, pull requests merged in 2025-09, with the labels that each got.

#597 Igor/mathieu/frontend openapi react query
  www/app/(app)/browse/_components/FilterSidebar.tsx
  www/app/(app)/browse/page.tsx
  www/app/(app)/rooms/page.tsx
  www/app/(app)/rooms/useRoomList.tsx
  www/app/(app)/transcripts/[transcriptId]/page.tsx
  www/app/(app)/transcripts/player.tsx
  www/app/(app)/transcripts/shareAndPrivacy.tsx
  www/app/(app)/transcripts/shareZulip.tsx
  www/app/(app)/transcripts/useParticipants.ts
  www/app/(app)/transcripts/useTopicWithWords.ts
  www/app/(app)/transcripts/useTranscript.ts
  www/app/(app)/transcripts/useWebRTC.ts
  www/app/lib/apiHooks.ts
  www/app/lib/useSessionStatus.ts
Labels: Review effort 2/5

#602 fix: align whisper transcriber api with parakeet
  server/docs/gpu/api-transcription.md
  server/gpu/modal_deployments/reflector_transcriber.py
  server/tests/test_gpu_modal_transcript.py
Labels: Review effort 3/5

#603 chore(main): release 0.9.0
  CHANGELOG.md
Labels: Review effort 1/5, autorelease: pending

#624 fix: auth post
  server/reflector/db/meetings.py
  www/app/lib/apiClient.tsx
Labels: Review effort 2/5

#630 fix: add follow_redirects=True on modal endpoint to prevent 303 See Others
  server/reflector/processors/file_diarization_modal.py
  server/reflector/processors/file_transcript_modal.py
Labels: Review effort 1/5

#647 fix: meeting useEffect frontend-only dedupe
  server/reflector/db/meetings.py
  server/reflector/views/rooms.py
  www/app/[roomName]/useRoomMeeting.tsx
Labels: Review effort 2/5

#649 chore: remove timeout-based auth session logic
  www/app/lib/apiClient.tsx
  www/app/lib/types.ts
Labels: Review effort 2/5

#648 chore(main): release 0.11.0
  CHANGELOG.md
Labels: Review effort 1/5, autorelease: pending

#646 fix: ignore player hotkeys for text inputs
  www/app/(app)/transcripts/player.tsx
Labels: Review effort 2/5

#608 feat: calendar integration
  server/migrations/versions/6025e9b2bef2_remove_one_active_meeting_per_room_.py
  server/migrations/versions/d4a1c446458c_add_grace_period_fields_to_meeting.py
  server/migrations/versions/d8e204bbf615_add_calendar.py
  server/migrations/versions/dc035ff72fd5_remove_grace_period_fields.py
  server/pyproject.toml
  server/reflector/auth/auth_jwt.py
  server/reflector/db/__init__.py
  server/reflector/db/calendar_events.py
  server/reflector/db/meetings.py
  server/reflector/db/rooms.py
  server/reflector/redis_cache.py
  server/reflector/services/ics_sync.py
  server/reflector/views/meetings.py
  server/reflector/views/rooms.py
  server/reflector/views/whereby.py
  server/reflector/worker/app.py
  server/reflector/worker/ics_sync.py
  server/reflector/worker/process.py
  server/test.ics
  server/tests/test_attendee_parsing_bug.ics
  server/tests/test_attendee_parsing_bug.py
  server/tests/test_calendar_event.py
  server/tests/test_ics_background_tasks.py
  server/tests/test_ics_sync.py
  server/tests/test_multiple_active_meetings.py
  server/tests/test_room_ics.py
  server/tests/test_room_ics_api.py
  server/uv.lock
  www/app/(app)/rooms/_components/ICSSettings.tsx
  www/app/(app)/rooms/_components/RoomList.tsx
  www/app/(app)/rooms/_components/RoomTable.tsx
  www/app/(app)/rooms/page.tsx
  www/app/[roomName]/MeetingSelection.tsx
  www/app/[roomName]/[meetingId]/constants.ts
  www/app/[roomName]/[meetingId]/page.tsx
  www/app/[roomName]/page.tsx
  www/app/[roomName]/room.tsx
  www/app/[roomName]/useRoomDefaultMeeting.tsx
  www/app/api/_error.ts
  www/app/api/schemas.gen.ts
  www/app/api/services.gen.ts
  www/app/api/types.gen.ts
  www/app/components/MeetingMinimalHeader.tsx
  www/app/lib/WherebyWebinarEmbed.tsx
  www/app/lib/apiHooks.ts
  www/app/lib/routes.ts
  www/app/lib/routesClient.ts
  www/app/lib/timeUtils.ts
  www/app/lib/wherebyClient.ts
  www/app/reflector-api.d.ts
  www/app/webinars/[title]/page.tsx
  www/package.json
  www/pnpm-lock.yaml
Labels: Review effort 4/5

#654 chore(main): release 0.12.0
  CHANGELOG.md
Labels: Review effort 1/5, autorelease: pending

#657 fix: production blocked because having existing meeting with room_id null
  server/migrations/versions/6dec9fb5b46c_make_meeting_room_id_required_and_add_.py
Labels: Review effort 1/5

#659 fix: rooms-page-calendar-ics-room-name-fix
  www/app/(app)/rooms/_components/ICSSettings.tsx
  www/app/(app)/rooms/page.tsx
Labels: Review effort 2/5

#660 fix: invalid cleanup call
  server/reflector/worker/cleanup.py
Labels: Review effort 1/5

#661 chore(main): release 0.13.0
  CHANGELOG.md
Labels: Review effort 1/5, autorelease: pending

#667 fix: TypeError on not all arguments converted during string formatting in logger
  server/reflector/worker/process.py
Labels: Review effort 1/5

#668 chore(main): release 0.13.1
  CHANGELOG.md
Labels: Review effort 1/5, autorelease: pending
